package problem2

import "fmt"

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

func FibConv(N int) int {
	A1 := 1
	A2 := 2
	var actSum int = 2
	for i := 3; A2 < N; i++ {
		Sum := (A1 + A2)
		A1 = A2
		A2 = Sum
		if Sum%2 == 0 {
			actSum = actSum + Sum
		}
		fmt.Printf("Term Index: %d, Term:%d, Sum: %d\n", i, Sum, actSum)
	}
	return actSum
}
